### ISSUE TITLE
Which file i need to run during the execution of the codes 

### ISSUE THREAD

**Issue by Siddhanth09** [KyleParkJong/NoC-simulator#2]
I  just need to understand how did u link the Digital design of a NOC with Python and how are validating it 

because when I tried your repo it had all the right  but I did not get how do u justify your results  like when I ran the code randomly 

which file structure  should I follow in order to get the  results

**Comment by Siddhanth09** [comment]
can u explain how do i set up the simulation env for python files to work

**Comment by KyleParkJong** [comment]
Thank you very much for your interest in my project. I have answered your email. I hope that answers your question.
